"use client";
import { useEffect, useState } from "react";
import { supabase } from "../../../lib/supabase";

const dinheiro=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const campo={border:"1px solid #dbe3ee",borderRadius:9,padding:"8px 10px",fontSize:12,background:"#fff"};
const caixa={border:"1px solid #e2e8f0",borderRadius:14,padding:14,background:"#fff"};
const tipos=["provento","desconto","afastamento_pago","afastamento_nao_pago","ferias","terco_ferias","decimo_terceiro","inss_decimo","emprestimo","devolucao","rescisao","aviso_previo","outro"];
const vazio={id:"",funcionario_id:"",tipo:"provento",descricao:"",referencia:0,valor:0,natureza:"provento",incide_inss:false,incide_fgts:false,incide_irrf:false,observacao:""};

export function FolhaMotorContabil({competencia,itens,onAtualizado}:{competencia:string;itens:any[];onAtualizado:()=>void}){
  const[regras,setRegras]=useState<any>(null),[eventos,setEventos]=useState<any[]>([]),[form,setForm]=useState<any>(vazio),[aberto,setAberto]=useState(false),[msg,setMsg]=useState("");
  const carregar=async()=>{if(!competencia)return;const[r,e]=await Promise.all([supabase.rpc("obter_regras_folha"),supabase.rpc("listar_eventos_folha",{p_competencia:competencia,p_funcionario_id:null})]);if(!r.error)setRegras(r.data);if(!e.error)setEventos(e.data||[])};
  useEffect(()=>{carregar()},[competencia]);
  const salvarRegras=async()=>{const{error}=await supabase.rpc("salvar_regras_folha",{p_regras:regras});if(error)return setMsg(error.message);setMsg("Regras salvas.");await recalcular()};
  const recalcular=async()=>{const{error}=await supabase.rpc("aplicar_calculos_contabeis_folha",{p_competencia:competencia});if(error)return setMsg(error.message);setMsg("Folha recalculada com as regras contábeis.");onAtualizado()};
  const salvarEvento=async()=>{if(!form.funcionario_id||!form.descricao||Number(form.valor)<=0)return setMsg("Informe colaborador, descrição e valor.");const{error}=await supabase.rpc("salvar_evento_folha",{p_evento:{...form,competencia}});if(error)return setMsg(error.message);setForm(vazio);await carregar();await recalcular()};
  const excluir=async(id:string)=>{const{error}=await supabase.rpc("excluir_evento_folha",{p_id:id});if(error)return setMsg(error.message);await carregar();await recalcular()};
  const n=(k:string,v:any)=>setRegras((r:any)=>({...r,[k]:Number(v)}));
  return <div style={{display:"grid",gap:12}}>
    <div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={()=>setAberto(!aberto)} style={{...campo,fontWeight:800,color:"#4338ca"}}>⚙ Regras e eventos da folha</button><button onClick={recalcular} style={{...campo,fontWeight:800}}>Recalcular custos</button>{msg&&<span style={{fontSize:11,color:"#475569",alignSelf:"center"}}>{msg}</span>}</div>
    {aberto&&<div style={{display:"grid",gap:12}}>
      {regras&&<div style={caixa}><h3 style={{margin:"0 0 10px"}}>Parâmetros contábeis</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8}}>{[["Divisor salário/dias","divisor_salario_dias"],["FGTS %","percentual_fgts"],["INSS patronal %","percentual_inss_patronal"],["RAT %","percentual_rat"],["Terceiros %","percentual_terceiros"],["Desconto VT %","percentual_vt_empregado"],["Dedução IRRF/dependente","deducao_irrf_dependente"],["Dedução simplificada IRRF","deducao_irrf_simplificada"],["Máx. DSR/mês","max_dsr_mes"]].map(([l,k])=><label key={k} style={{fontSize:10,color:"#64748b"}}>{l}<input type="number" step="0.01" value={regras[k]??0} onChange={e=>n(k,e.target.value)} style={{...campo,width:"100%",boxSizing:"border-box",marginTop:3}}/></label>)}</div><div style={{display:"flex",gap:14,flexWrap:"wrap",marginTop:10,fontSize:11}}>{[["calcular_dsr_faltas","Descontar DSR por falta"],["usar_deducao_irrf_simplificada","Usar dedução simplificada IRRF"],["provisionar_decimo","Provisionar 13º"],["provisionar_ferias","Provisionar férias + 1/3"]].map(([k,l])=><label key={k}><input type="checkbox" checked={!!regras[k]} onChange={e=>setRegras((r:any)=>({...r,[k]:e.target.checked}))}/> {l}</label>)}</div><button onClick={salvarRegras} style={{...campo,marginTop:10,fontWeight:800}}>Salvar parâmetros</button></div>}
      <div style={caixa}><h3 style={{margin:"0 0 4px"}}>Eventos variáveis da competência</h3><p style={{fontSize:11,color:"#64748b"}}>Férias, 1/3, 13º, afastamentos, empréstimos, devoluções, aviso-prévio e rescisão entram aqui e recalculam as bases automaticamente.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8}}><select value={form.funcionario_id} onChange={e=>setForm({...form,funcionario_id:e.target.value})} style={campo}><option value="">Colaborador</option>{itens.map(i=><option key={i.funcionario_id} value={i.funcionario_id}>{i.nome}</option>)}</select><select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})} style={campo}>{tipos.map(t=><option key={t}>{t.replaceAll("_"," ")}</option>)}</select><select value={form.natureza} onChange={e=>setForm({...form,natureza:e.target.value})} style={campo}><option value="provento">Provento</option><option value="desconto">Desconto</option><option value="informativo">Informativo</option></select><input placeholder="Descrição" value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})} style={campo}/><input type="number" placeholder="Referência" value={form.referencia||""} onChange={e=>setForm({...form,referencia:Number(e.target.value)})} style={campo}/><input type="number" placeholder="Valor" value={form.valor||""} onChange={e=>setForm({...form,valor:Number(e.target.value)})} style={campo}/></div><div style={{display:"flex",gap:12,marginTop:8,fontSize:11}}>{[["incide_inss","INSS"],["incide_fgts","FGTS"],["incide_irrf","IRRF"]].map(([k,l])=><label key={k}><input type="checkbox" checked={!!form[k]} onChange={e=>setForm({...form,[k]:e.target.checked})}/> Incide {l}</label>)}<button onClick={salvarEvento} style={{...campo,fontWeight:800,marginLeft:"auto"}}>{form.id?"Atualizar":"Adicionar evento"}</button></div>
      {eventos.map(e=><div key={e.id} style={{display:"grid",gridTemplateColumns:"1fr 1.4fr 100px 120px",gap:8,padding:"8px 0",borderTop:"1px solid #eef2f7",fontSize:11}}><span>{itens.find(i=>i.funcionario_id===e.funcionario_id)?.nome||"Colaborador"}</span><span><b>{e.descricao}</b><br/>{e.tipo.replaceAll("_"," ")} · {e.natureza}</span><b>{dinheiro(e.valor)}</b><span><button onClick={()=>setForm({...e})}>Editar</button> {!e.automatico&&<button onClick={()=>excluir(e.id)}>Excluir</button>}</span></div>)}</div>
    </div>}
  </div>
}
