-- Planos ativos/inativos, responsavel de equipe e terceiro nivel de filas.
-- Inclusao aditiva: nenhum plano ou vinculo historico de proposta e removido.

create table if not exists public.proposta_planos_status (
  id bigint generated by default as identity primary key,
  plano text not null,
  plano_chave text not null unique,
  ativo boolean not null default true,
  atualizado_por text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.proposta_planos_status enable row level security;
drop policy if exists "proposta_planos_status_leitura" on public.proposta_planos_status;
create policy "proposta_planos_status_leitura" on public.proposta_planos_status
  for select to authenticated using (true);
drop policy if exists "proposta_planos_status_admin" on public.proposta_planos_status;
create policy "proposta_planos_status_admin" on public.proposta_planos_status
  for all to authenticated
  using (coalesce(public.usuario_pode_administrar_financeiro(), false))
  with check (coalesce(public.usuario_pode_administrar_financeiro(), false));

grant select on public.proposta_planos_status to authenticated;

create or replace function public.salvar_proposta_plano_status(p_plano text, p_ativo boolean)
returns public.proposta_planos_status
language plpgsql security definer set search_path = public as $$
declare
  v_resultado public.proposta_planos_status;
  v_plano text := trim(coalesce(p_plano, ''));
  v_chave text;
begin
  if not coalesce(public.usuario_pode_administrar_financeiro(), false) then
    raise exception 'Somente administradores podem ativar ou inativar planos.' using errcode = '42501';
  end if;
  if v_plano = '' then raise exception 'Informe o plano.'; end if;
  v_chave := public.normalizar_plano_comissao(v_plano);
  insert into public.proposta_planos_status(plano, plano_chave, ativo, atualizado_por, updated_at)
  values(v_plano, v_chave, coalesce(p_ativo, true), lower(coalesce(auth.jwt()->>'email', '')), now())
  on conflict (plano_chave) do update set
    plano = excluded.plano, ativo = excluded.ativo,
    atualizado_por = excluded.atualizado_por, updated_at = now()
  returning * into v_resultado;
  update public.fin_comissao_planos
  set ativo = coalesce(p_ativo, true), updated_at = now(), atualizado_por = lower(coalesce(auth.jwt()->>'email', ''))
  where public.normalizar_plano_comissao(plano) = v_chave;
  return v_resultado;
end;
$$;

revoke all on function public.salvar_proposta_plano_status(text,boolean) from public;
grant execute on function public.salvar_proposta_plano_status(text,boolean) to authenticated;

alter table public.filas
  add column if not exists responsavel_usuario_id bigint,
  add column if not exists valor_comissao_supervisor numeric;

create index if not exists filas_responsavel_usuario_idx
  on public.filas(responsavel_usuario_id) where responsavel_usuario_id is not null;

create table if not exists public.filas_operacionais (
  id bigint generated by default as identity primary key,
  equipe_id bigint not null,
  nome text not null,
  descricao text,
  cor text not null default '#0ea5e9',
  icone text not null default '📥',
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists filas_operacionais_equipe_nome_uidx
  on public.filas_operacionais(equipe_id, lower(trim(nome)));
create index if not exists filas_operacionais_equipe_idx
  on public.filas_operacionais(equipe_id) where ativo;

alter table public.filas_operacionais enable row level security;
drop policy if exists "filas_operacionais_leitura" on public.filas_operacionais;
create policy "filas_operacionais_leitura" on public.filas_operacionais
  for select to authenticated using (true);
drop policy if exists "filas_operacionais_admin" on public.filas_operacionais;
create policy "filas_operacionais_admin" on public.filas_operacionais
  for all to authenticated
  using (coalesce(public.usuario_pode_administrar_financeiro(), false))
  with check (coalesce(public.usuario_pode_administrar_financeiro(), false));

grant select, insert, update, delete on public.filas_operacionais to authenticated;
grant usage, select on sequence public.filas_operacionais_id_seq to authenticated;

comment on table public.proposta_planos_status is
  'Controla disponibilidade do plano em novas propostas sem alterar propostas historicas.';
comment on column public.filas.responsavel_usuario_id is
  'Usuario responsavel pela equipe, usado na apuracao de comissao de supervisor.';
comment on table public.filas_operacionais is
  'Terceiro nivel organizacional: Empresa/PDV (equipes) -> Equipe (filas) -> Fila operacional.';
